openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: 'Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.'
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics Admin accounts API
  version: v1beta
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://analyticsadmin.googleapis.com/$discovery/rest?version=v1beta
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: analyticsadmin
servers:
- url: https://analyticsadmin.googleapis.com/
tags:
- name: accounts
paths:
  /v1beta/accounts:
    get:
      description: 'Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: "trashed") accounts are excluded by default. Returns an empty list if no relevant accounts are found.'
      operationId: analyticsadmin.accounts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accounts
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1beta/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin.accounts.provisionAccountTicket
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1beta/{account}:searchChangeHistoryEvents:
    post:
      description: Searches through all changes to an account or its children given the specified set of filters.
      operationId: analyticsadmin.accounts.searchChangeHistoryEvents
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2