openapi: 3.2.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Views and manages your Google Analytics data.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics User Deletion API
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://analytics.googleapis.com/$discovery/rest?version=v3
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: analytics
servers:
- url: https://analytics.googleapis.com/analytics/v3
tags:
- name: userDeletion
paths:
  /userDeletion/userDeletionRequests:upsert:
    post:
      description: Insert or update a user deletion requests.
      operationId: analytics.userDeletion.userDeletionRequest.upsert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.user.deletion
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.user.deletion
      tags:
      - userDeletion
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google Analytics data
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.provision: Create a new Google Analytics account along with its default property and view
            https://www.googleapis.com/auth/analytics.readonly: View your Google Analytics data
            https://www.googleapis.com/auth/analytics.user.deletion: Manage Google Analytics user deletion requests
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google Analytics data
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.provision: Create a new Google Analytics account along with its default property and view
            https://www.googleapis.com/auth/analytics.readonly: View your Google Analytics data
            https://www.googleapis.com/auth/analytics.user.deletion: Manage Google Analytics user deletion requests
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2